name: ğŸ—ï¸ Build
on: push

jobs:
  build:
    uses: acidicoala/KoalaBox/.github/workflows/build.yml@7db439061fbf53667bbb61c99404845c643de2b3
    with:
      module: '[ "SmokeAPI" ]'
      os: '[ "Windows", "Linux" ]'
      bitness: '[ 32, 64 ]'
