name: ğŸ—ï¸ Project Build
on: push

jobs:
  build:
    name: ${{ github.event.input.module }}-${{ matrix.os }}-${{ matrix.bitness }}

    strategy:
      fail-fast: false
      matrix:
        module: [ SmokeAPI ]
        os: [ Linux, Windows ]
        bitness: [ 32, 64 ]

    uses: acidicoala/SmokeAPI/.github/workflows/kb-build.yml@master
    with:
      module: ${{ matrix.module }}
      os: ${{ matrix.os }}
      bitness: ${{ matrix.bitness }}
