name: ğŸ—ï¸ Build
on: push

jobs:
  build:
    name: ğŸ—ï¸ Build
    uses: acidicoala/KoalaBox/.github/workflows/build.yml@346ce0d6402107f5ad22e9ffb0a277e5c00423a0
    with:
      #language=json
      module: '[ "SmokeAPI" ] '

      #language=json
      os: '[ "Windows", "Linux" ]'

      #language=json
      bitness: '[ 32, 64 ]'
