name: ğŸ—ï¸ Build
on: push

jobs:
  build:
    name: ğŸ—ï¸ Build
    uses: acidicoala/KoalaBox/.github/workflows/build.yml@465481c8cd01ab403cff7394cb07eb4430dccfab
    with:
      #language=json
      module: '[ "SmokeAPI" ] '

      #language=json
      os: '[ "Windows", "Linux" ]'

      #language=json
      bitness: '[ 32, 64 ]'
