name: ğŸ—ï¸ Build
on: push

jobs:
  build:
    name: ğŸ—ï¸ Build
    uses: acidicoala/KoalaBox/.github/workflows/build.yml@643f6e45cc1630070c79fa3915e2b110d128461b
    with:
      #language=json
      module: '[ "SmokeAPI" ] '

      #language=json
      os: '[ "Windows", "Linux" ]'

      #language=json
      bitness: '[ 32, 64 ]'
