name: Matrix Build

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ Linux, Windows ]
        bitness: [ 32, 64 ]

    uses: acidicoala/KoalaBox/.github/workflows/build-cmake.yml@master
    with:
      module: SmokeAPI
      os: ${{ matrix.os }}
      bitness: ${{ matrix.bitness }}
